### PR TITLE
Add kde to the list of smartcard capable PAM services

### LINKED ISSUE #234: Need to add pam service name for plasma screen locker
The KDE 5/Plasma desktop uses the pam service name of "kde" for the screen lock.  I think this just need to be added to https://github.com/authselect/authselect/blob/master/profiles/sssd/system-auth#L5 but I'm not sure.

### PR DESCRIPTION
**Pull request by opoplawski**
Resolves #234

### CODE REVIEW

**Comment by sumit-bose** [comment]
Hi,

I agree with adding "kde" to the list of the PAM services which can handle local Smartcard authentication. But I think it is not expected to add the change to all the `*.po` files. It should be sufficient to add the change `authselect-profiles.5.adoc` and the `*.po` files are updated by Makefile magic. @pbrezina, am I right here?

bye,
Sumit

**Comment by pbrezina** [comment]
Yes, you are right. @opoplawski Thank you for your patch, could you please remove the changes in *po files?

**Comment by opoplawski** [comment]
Done.  I assuming that included the .pot file as well.

**Comment by pbrezina** [comment]
Thank you, ack.

**Pull request merged**
