### PR TITLE
profiles: try_first_pass has no effect on pam_unix and pam_pwquality

### PR DESCRIPTION
**Pull request by pbrezina**
Resolves:
https://github.com/authselect/authselect/issues/247

### CODE REVIEW

**Comment by ikerexxe** [comment]
I think that the man pages should also be changed to avoid confusion.

Apart from that everything looks fine to me.

**Comment by pbrezina** [comment]
Makes sense. See new patch.

**Comment by ikerexxe** [comment]
LGTM!

**Comment by thalman** [comment]
ACK

**Pull request merged**
